services:
  dyslexic_db:
    image: postgres:latest
    container_name: dyslexic_postgres
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - pgdata:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/var/lib/postgresql/data/18/pg_hba.conf
    networks:
      - dyslexic_backend_network

  dyslexic_backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: http://host.docker.internal:10808
        HTTPS_PROXY: http://host.docker.internal:10808
        http_proxy: http://host.docker.internal:10808
        https_proxy: http://host.docker.internal:10808
        NO_PROXY: localhost,127.0.0.1
      extra_hosts:
        - "host.docker.internal:host-gateway"
    image: ghcr.io/niflheimdevs/dyslexics-clock
    container_name: dyslexic_backend
    restart: always
    depends_on:
      - dyslexic_db
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    networks:
      - dyslexic_backend_network

volumes:
  pgdata:

networks:
  dyslexic_backend_network:
